# Generated by Django 2.0.6 on 2018-08-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eces', '0002_filiere_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='image',
            field=models.FileField(default='Departement/images/', upload_to='Departement/images/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.FileField(default='Document/images/', upload_to='Document/images/'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='image',
            field=models.FileField(default='Departement/images/', upload_to='Departement/images/'),
        ),
    ]
