# Generated by Django 2.0.6 on 2018-08-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eces', '0003_auto_20180817_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='image',
            field=models.FileField(default='Departement/images/images39.png', upload_to='Departement/images/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.FileField(default='Document/images/images34.jpeg', upload_to='Document/images/'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='image',
            field=models.FileField(default='Departement/images/images39.png', upload_to='Departement/images/'),
        ),
    ]
